name: 'GraphQL API docs generate'
description: 'Generate GraphQL API documents.'
inputs:
  spectaql-config-path:
    description: 'Path of the spectaql configuration file.'
    required: true
  output-dir:
    description: 'Outpu directory of docs.'
    required: true
  spectaql-args:
    description: 'Arguments of the spectaql command. (ex: "--app-dir path/to/app")'
    required: false
    default: ''

runs:
  using: 'composite'
  env:
    OUTPUT_DIR: ${{ inputs.output-dir }}
    TEMP_OUTPUT_DIR: './temp-output-graphql-api-docs-generate'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install spectaql
      run: |
        npm install -g spectaql

    - name: Run spectaql
      run: |
        npx spectaql "${{ inputs.spectaql-config-path }}" --target-dir "${TEMP_OUTPUT_DIR}"  ${{ inputs.spectaql-args }}

    - name: Overwrite docs
      run: |
        rm -rf "${OUTPUT_DIR}"
        mv "${TEMP_OUTPUT_DIR}" "${OUTPUT_DIR}"

    - name: Cleanup temporary dir
      if: ${{ always() }}
      run: |
        rm -rf "${TEMP_OUTPUT_DIR}"

