name: 'GraphQL API docs generate'
description: 'Generate GraphQL API documents.'
inputs:
  spectaql-config-path:
    description: 'Path of the spectaql configuration file.'
    required: true
  output-dir:
    description: 'Outpu directory of docs.'
    required: true
  temp-output-dir:
    description: 'Temporary output dir.'
    required: false
    default: './temp-output-graphql-api-docs-generate'
  spectaql-args:
    description: 'Arguments of the spectaql command. (ex: "--app-dir path/to/app")'
    required: false
    default: ''
  spectaql-version:
    description: 'The version of spectaql'
    required: false
    default: '~0.12.0'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install spectaql
      shell: bash
      run: |
        echo "\033[0;31m*** Install spectaql ***\033[0m"
        npm install -g "spectaql@${{ inputs.spectaql-version }}"

    - name: Setup temp dir
      shell: bash
      run: |
        echo "\033[0;31m*** Setup temp dir ***\033[0m"
        rm -rf "${{ inputs.temp-output-dir }}"
        mkdir "${{ inputs.temp-output-dir }}"

    - name: Run spectaql
      shell: bash
      run: |
        echo "\033[0;31m*** Run spectaql ***\033[0m"
        npx spectaql "${{ inputs.spectaql-config-path }}" --target-dir "${{ inputs.temp-output-dir }}" ${{ inputs.spectaql-args }}

    - name: Overwrite docs
      shell: bash
      run: |
        echo "\033[0;31m*** Overwrite docs ***\033[0m"
        rm -rf "${{ inputs.output-dir }}"
        mkdir -p "$(dirname ${{ inputs.output-dir }})"
        mv "${{ inputs.temp-output-dir }}" "${{ inputs.output-dir }}"

    # SEE https://github.com/stefanzweifel/git-auto-commit-action
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automatically generate GraphQL docs"

