name: 'GraphQL API docs generate'
description: 'Generate GraphQL API documents.'
inputs:
  spectaql-config-path:
    description: 'Path of the spectaql configuration file.'
    required: true
  output-dir:
    description: 'Outpu directory of docs.'
    required: true
  temp-output-dir:
    description: 'Temporary output dir.'
    required: false
    default: './temp-output-graphql-api-docs-generate'
  spectaql-args:
    description: 'Arguments of the spectaql command. (ex: "--app-dir path/to/app")'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install spectaql
      run: |
        npm install -g spectaql

    - name: Run spectaql
      run: |
        npx spectaql "${{ inputs.spectaql-config-path }}" --target-dir "${{ inputs.temp-output-dir }}" ${{ inputs.spectaql-args }}

    - name: Overwrite docs
      run: |
        rm -rf "${{ inputs.output-dir }}"
        mv "${{ inptus.temp-output-dir }}" "${{ inputs.output-dir }}"

