name: 'GraphQL API docs generate'
description: 'Generate GraphQL API documents.'
inputs:
  spectaql-config-path:
    description: 'Path of the spectaql configuration file.'
    required: true
  output-dir:
    description: 'Outpu directory of docs.'
    required: true
  temp-output-dir:
    description: 'Temporary output dir.'
    required: false
    default: './temp-output-graphql-api-docs-generate'
  spectaql-args:
    description: 'Arguments of the spectaql command. (ex: "--app-dir path/to/app")'
    required: false
    default: ''
  spectaql-version:
    description: 'The version of spectaql'
    required: false
    default: '~0.12.0'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install spectaql
      shell: bash
      run: |
        echo "*** Install spectaql ***"
        npm install -g "spectaql@${{ inputs.spectaql-version }}"

    - name: Setup temp dir
      shell: bash
      run: |
        echo "*** Setup temp dir ***"
        rm -rf "${{ inputs.temp-output-dir }}"
        mkdir "${{ inputs.temp-output-dir }}"

    - name: Run spectaql
      shell: bash
      run: |
        echo "*** Run spectaql ***"
        npx spectaql "${{ inputs.spectaql-config-path }}" --target-dir "${{ inputs.temp-output-dir }}" ${{ inputs.spectaql-args }}

    - name: Overwrite docs
      shell: bash
      run: |
        echo "*** Overwrite docs ***"
        rm -rf "${{ inputs.output-dir }}"
        mkdir -p "${{ inputs.output-dir }}"
        mv "${{ inputs.temp-output-dir }}" "${{ inputs.output-dir }}"

    - name: Show result
      shell: bash
      run: |
        echo "*** Show result ***"
        ls -lR

